name: Deploy to Azure Container Instances

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: |
          python -m pip install --upgrade pip
          pip install mlflow azureml-mlflow

      - name: Download best model + artifact
        run: |
          export AZURE_RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}
          export AZURE_WORKSPACE_NAME=${{ secrets.AZURE_WORKSPACE_NAME }}
          export TRAINING_PIPELINE_NAME=${{ secrets.TRAINING_PIPELINE_NAME }}
          bash credit_scoring_app/bash_scripts/download_best_model_pointer.sh

      - name: Deploy backend
        run: |
          bash credit_scoring_app/bash_scripts/deploy_backend.sh \
            ${{ secrets.ACR_NAME }} \
            ${{ secrets.AZURE_RESOURCE_GROUP }} \
            ${{ secrets.BACKEND_CONTAINER_NAME }} \
            ${{ secrets.ACI_LOCATION }}

      - name: Deploy frontend
        run: |
          bash credit_scoring_app/bash_scripts/deploy_frontend.sh \
            ${{ secrets.ACR_NAME }} \
            ${{ secrets.AZURE_RESOURCE_GROUP }} \
            ${{ secrets.FRONTEND_CONTAINER_NAME }} \
            ${{ secrets.ACI_LOCATION }}
